name: API Tests

on:
  # Run on push to main branch
  push:
    branches: [ main, master ]

  # Run on pull requests
  pull_request:
    branches: [ main, master ]

  # Run daily at 9:00 AM UTC (щоденний запуск)
  schedule:
    - cron: '0 9 * * *'

  # Allow manual trigger
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        uv sync

    - name: Run linter
      run: |
        uv run ruff check .
      continue-on-error: true

    - name: Run tests
      run: |
        uv run pytest dummyjson/tests/api/test_assignment.py -v --alluredir=allure-results

    - name: Generate Allure report
      if: always()
      run: |
        sudo apt-get update
        sudo apt-get install -y allure
        allure generate allure-results -o allure-report --clean
      continue-on-error: true

    - name: Upload Allure results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: allure-results/
        retention-days: 30

    - name: Upload Allure report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report/
        retention-days: 30

    - name: Test Report Summary
      if: always()
      run: |
        echo "## Test Results" >> $GITHUB_STEP_SUMMARY
        echo "Tests completed. Check artifacts for detailed Allure reports." >> $GITHUB_STEP_SUMMARY
